### ISSUE TITLE
那个转圈效果 咋不弄个gif图片呢

### ISSUE THREAD

**Issue by jj89757hhb** [jinxiansen/JHUD#1]

**Comment by Jinxiansen** [comment]
好，后面会加入。

**Comment by Jinxiansen** [comment]
你好，已经支持Gif 图片效果，可下载最新版查看。

**Comment by LeaderBoy** [comment]
用了         hud?.showAtView(self.view, hudType: JHUDLoadingType.GifImage)
为什么我把加载的动画加到哪个view上哪个view就不能改变背景色了

**Comment by Jinxiansen** [comment]
可以通过改变hudView的背景色。

**Comment by LeaderBoy** [comment]
哦好的,谢谢,我一直在改view的背景

**Comment by Jinxiansen** [comment]
吃惊...
