### ISSUE TITLE
pod 安装失败

### ISSUE THREAD

**Issue by wing3501** [jinxiansen/JHUD#2]
![image](https://cloud.githubusercontent.com/assets/14328161/16976459/98b4bc16-4e81-11e6-87aa-c03829cbb867.png)

**Comment by Jinxiansen** [comment]
<img width="475" alt="2016-07-20 2 03 09" src="https://cloud.githubusercontent.com/assets/16829428/16976641/b929f5a0-4e82-11e6-8388-d61febb91470.png">
我在搜的时候是 有的，
两个方法：
1，更新一下本地pod库，使用pod setup 命令，然后再搜。
2，你可以尝试手动导入JHUD文件夹。
