### ISSUE TITLE
indicatorViewSize这个是做什么的

### ISSUE THREAD

**Issue by JIAZoro** [jinxiansen/JHUD#5]
有时只是想显示自定义的动画，却发现下面有一块视图，不知道是做什么用的，

```
//[self configureBaseInfo];
-(void)configureBaseInfo
{
    self.backgroundColor = [UIColor groupTableViewBackgroundColor];
    self.indicatorViewSize = CGSizeMake(100, 100);
}
```

把这个注释掉//[self configureBaseInfo];，发现达到了自己想要的效果。在添加文字，也是可以正常显示的，那么问题来了，这个是做啥很么用的，注释掉会有什么影响没

**Comment by Jinxiansen** [comment]
indicatorViewSize 指定显示的图片/动图的大小。
道友使用正常的话，注释掉也可以。
