### ISSUE TITLE
螢幕打橫時

### ISSUE THREAD

**Issue by ghost** [jinxiansen/JHUD#6]
您好，我有個疑問
當我螢幕打橫時卻發生這樣的問題

![simulator screen shot 2017 3 2 10 12 44](https://cloud.githubusercontent.com/assets/19277294/23490059/f69d2aba-ff30-11e6-9b35-fc80ee11e03d.png)

不曉得是不是我寫錯了什麼？(附上代碼)
```objc
@property (nonatomic, strong) JHUD *hudView;
- (void)viewDidLoad
{
    [super viewDidLoad];
    [self showHUD];
  _hudView = [[JHUD alloc]initWithFrame:self.view.bounds];
  _hudView.messageLabel.text = @"hello ,this is a circle animation";
}
-(void)showHUD {
  [_hudView showAtView:self.view hudType:JHUDLoadingTypeDot];
}
```

**Comment by Jinxiansen** [comment]
<img width="475" alt="1" src="https://cloud.githubusercontent.com/assets/16829428/23490251/5a0c3e78-ff32-11e6-97cc-9d3ade7b5c71.png">
你这里没有初始化呢，就开始调用 show 了？
至于横屏显示的问题，你可以看 Demo 里边，在 viewWillLayoutSubviews 里更新 hud frame。
<img width="738" alt="2" src="https://cloud.githubusercontent.com/assets/16829428/23490297/a83f8e4c-ff32-11e6-996e-95a5bab7bd3b.png">

**Comment by ghost** [comment]
謝謝大神，我打太快打錯了。
問題已經解決。

**Comment by Jinxiansen** [comment]
共同学习，共同进步。
我是菜鸟。😬
